import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import MovieList from './Components/MovieList'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.mainContainer}>
          <div className={styles.contentContainer}>
            <div className={styles.featuredContent} style={{background:'linear-gradient(to bottom, rgba(0,0,0,0),#151515), url("/images/f-1.jpg")'}}>
              <Image src="/images/f-t-1.png" width={300} height={150} className={styles.featuredTitle} alt="featured title"/>
              <p className={styles.featuredDesc}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Error animi magnam quos ducimus impedit repellendus labore et nostrum dicta, esse aperiam veniam quia dolorem ab voluptate explicabo quasi, nisi ea.
              </p>
              <button className={styles.featuredButton}>WATCH</button>
            </div>


            {/*movies list container*/}
            <MovieList/>
            <MovieList/>
            {/* another featured banner */}
            <div className={styles.featuredContent} style={{background:'linear-gradient(to bottom, rgba(0,0,0,0),#151515), url("/images/f-2.jpg")'}}>
                <Image src="/images/f-t-2.png" width={300} height={150} className={styles.featuredTitle} alt="featured title"/>
                <p className={styles.featuredDesc}>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Error animi magnam quos ducimus impedit repellendus labore et nostrum dicta, esse aperiam veniam quia dolorem ab voluptate explicabo quasi, nisi ea.
                </p>
                <button className={styles.featuredButton}>WATCH</button>
            </div>
            <MovieList/>
            <MovieList/>
            
          </div>
        </div>
      </main>
    </div>
  )
}
